### ISSUE TITLE
Submit to Plugin Marketplace

### ISSUE THREAD

**Issue by mickmister** [svelle/mattermost-spoiler-plugin#1]
@svelle Do you have any intention of submitting this to the marketplace?

Here are the docs on preparing the plugin for submission if you're interested in including the plugin in the marketplace: https://developers.mattermost.com/integrate/plugins/community-plugin-marketplace

**Comment by svelle** [comment]
Hey @mickmister sorry didn't see this. Yeah I'm down for that. I'll look into the docs and try and submit it soon!

(need to discuss the new better call saul episodes without spoiling anyone :D)

**Comment by svelle** [comment]
submitted it
